/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GithubStatusRouteImport } from './routes/github-status'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContentRouteImport } from './routes/content'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as SettingsApiRouteImport } from './routes/settings.api'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as ContentIdRouteImport } from './routes/content.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiPerplexitySearchRouteImport } from './routes/api/perplexity.search'
import { Route as ApiLiveStatusRouteImport } from './routes/api/live.status'
import { Route as ApiGooglePagespeedRouteImport } from './routes/api/google.pagespeed'
import { Route as ApiGoogleGscSitesRouteImport } from './routes/api/google.gsc-sites'
import { Route as ApiGoogleGscImportRouteImport } from './routes/api/google.gsc-import'
import { Route as ApiGoogleGa4TrafficRouteImport } from './routes/api/google.ga4-traffic'
import { Route as ApiGoogleGa4SummaryRouteImport } from './routes/api/google.ga4-summary'
import { Route as ApiGoogleGa4PropertiesRouteImport } from './routes/api/google.ga4-properties'
import { Route as ApiGoogleGa4ConversionsRouteImport } from './routes/api/google.ga4-conversions'
import { Route as ApiGoogleConnectionRouteImport } from './routes/api/google.connection'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google.callback'
import { Route as ApiGoogleAdsDataRouteImport } from './routes/api/google.ads-data'
import { Route as ApiGoogleAdsCustomersRouteImport } from './routes/api/google.ads-customers'
import { Route as ApiCanonryCreateProjectRouteImport } from './routes/api/canonry.create-project'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai.generate'
import { Route as ApiAhrefsOverviewRouteImport } from './routes/api/ahrefs.overview'
import { Route as ApiAgentRunAgentRouteImport } from './routes/api/agent.run-agent'
import { Route as ApiAgentRunRouteImport } from './routes/api/agent.run'
import { Route as ApiAgentMemoryRouteImport } from './routes/api/agent.memory'
import { Route as ApiAgentJobRouteImport } from './routes/api/agent.job'
import { Route as ApiAgentAgentsRouteImport } from './routes/api/agent.agents'
import { Route as ApiAdminPopulateRouteImport } from './routes/api/admin.populate'
import { Route as ApiLiveCanonryOverviewRouteImport } from './routes/api/live.canonry.overview'
import { Route as ApiLiveCanonryAiVisibilityRouteImport } from './routes/api/live.canonry.ai-visibility'
import { Route as ApiGoogleOauthStartRouteImport } from './routes/api/google.oauth.start'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubStatusRoute = GithubStatusRouteImport.update({
  id: '/github-status',
  path: '/github-status',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const SettingsApiRoute = SettingsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => SettingsRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPerplexitySearchRoute = ApiPerplexitySearchRouteImport.update({
  id: '/api/perplexity/search',
  path: '/api/perplexity/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveStatusRoute = ApiLiveStatusRouteImport.update({
  id: '/api/live/status',
  path: '/api/live/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGooglePagespeedRoute = ApiGooglePagespeedRouteImport.update({
  id: '/api/google/pagespeed',
  path: '/api/google/pagespeed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGscSitesRoute = ApiGoogleGscSitesRouteImport.update({
  id: '/api/google/gsc-sites',
  path: '/api/google/gsc-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGscImportRoute = ApiGoogleGscImportRouteImport.update({
  id: '/api/google/gsc-import',
  path: '/api/google/gsc-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGa4TrafficRoute = ApiGoogleGa4TrafficRouteImport.update({
  id: '/api/google/ga4-traffic',
  path: '/api/google/ga4-traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGa4SummaryRoute = ApiGoogleGa4SummaryRouteImport.update({
  id: '/api/google/ga4-summary',
  path: '/api/google/ga4-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGa4PropertiesRoute = ApiGoogleGa4PropertiesRouteImport.update({
  id: '/api/google/ga4-properties',
  path: '/api/google/ga4-properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGa4ConversionsRoute = ApiGoogleGa4ConversionsRouteImport.update({
  id: '/api/google/ga4-conversions',
  path: '/api/google/ga4-conversions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleConnectionRoute = ApiGoogleConnectionRouteImport.update({
  id: '/api/google/connection',
  path: '/api/google/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAdsDataRoute = ApiGoogleAdsDataRouteImport.update({
  id: '/api/google/ads-data',
  path: '/api/google/ads-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAdsCustomersRoute = ApiGoogleAdsCustomersRouteImport.update({
  id: '/api/google/ads-customers',
  path: '/api/google/ads-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanonryCreateProjectRoute = ApiCanonryCreateProjectRouteImport.update({
  id: '/api/canonry/create-project',
  path: '/api/canonry/create-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAhrefsOverviewRoute = ApiAhrefsOverviewRouteImport.update({
  id: '/api/ahrefs/overview',
  path: '/api/ahrefs/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunAgentRoute = ApiAgentRunAgentRouteImport.update({
  id: '/api/agent/run-agent',
  path: '/api/agent/run-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunRoute = ApiAgentRunRouteImport.update({
  id: '/api/agent/run',
  path: '/api/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMemoryRoute = ApiAgentMemoryRouteImport.update({
  id: '/api/agent/memory',
  path: '/api/agent/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentJobRoute = ApiAgentJobRouteImport.update({
  id: '/api/agent/job',
  path: '/api/agent/job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAgentsRoute = ApiAgentAgentsRouteImport.update({
  id: '/api/agent/agents',
  path: '/api/agent/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPopulateRoute = ApiAdminPopulateRouteImport.update({
  id: '/api/admin/populate',
  path: '/api/admin/populate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveCanonryOverviewRoute = ApiLiveCanonryOverviewRouteImport.update({
  id: '/api/live/canonry/overview',
  path: '/api/live/canonry/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveCanonryAiVisibilityRoute =
  ApiLiveCanonryAiVisibilityRouteImport.update({
    id: '/api/live/canonry/ai-visibility',
    path: '/api/live/canonry/ai-visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleOauthStartRoute = ApiGoogleOauthStartRouteImport.update({
  id: '/api/google/oauth/start',
  path: '/api/google/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/content': typeof ContentRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/geo': typeof GeoRoute
  '/github-status': typeof GithubStatusRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/content/$id': typeof ContentIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/settings/api': typeof SettingsApiRoute
  '/tasks/$id': typeof TasksIdRoute
  '/api/admin/populate': typeof ApiAdminPopulateRoute
  '/api/agent/agents': typeof ApiAgentAgentsRoute
  '/api/agent/job': typeof ApiAgentJobRoute
  '/api/agent/memory': typeof ApiAgentMemoryRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/run-agent': typeof ApiAgentRunAgentRoute
  '/api/ahrefs/overview': typeof ApiAhrefsOverviewRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/canonry/create-project': typeof ApiCanonryCreateProjectRoute
  '/api/google/ads-customers': typeof ApiGoogleAdsCustomersRoute
  '/api/google/ads-data': typeof ApiGoogleAdsDataRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connection': typeof ApiGoogleConnectionRoute
  '/api/google/ga4-conversions': typeof ApiGoogleGa4ConversionsRoute
  '/api/google/ga4-properties': typeof ApiGoogleGa4PropertiesRoute
  '/api/google/ga4-summary': typeof ApiGoogleGa4SummaryRoute
  '/api/google/ga4-traffic': typeof ApiGoogleGa4TrafficRoute
  '/api/google/gsc-import': typeof ApiGoogleGscImportRoute
  '/api/google/gsc-sites': typeof ApiGoogleGscSitesRoute
  '/api/google/pagespeed': typeof ApiGooglePagespeedRoute
  '/api/live/status': typeof ApiLiveStatusRoute
  '/api/perplexity/search': typeof ApiPerplexitySearchRoute
  '/api/google/oauth/start': typeof ApiGoogleOauthStartRoute
  '/api/live/canonry/ai-visibility': typeof ApiLiveCanonryAiVisibilityRoute
  '/api/live/canonry/overview': typeof ApiLiveCanonryOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/content': typeof ContentRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/geo': typeof GeoRoute
  '/github-status': typeof GithubStatusRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/content/$id': typeof ContentIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/settings/api': typeof SettingsApiRoute
  '/tasks/$id': typeof TasksIdRoute
  '/api/admin/populate': typeof ApiAdminPopulateRoute
  '/api/agent/agents': typeof ApiAgentAgentsRoute
  '/api/agent/job': typeof ApiAgentJobRoute
  '/api/agent/memory': typeof ApiAgentMemoryRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/run-agent': typeof ApiAgentRunAgentRoute
  '/api/ahrefs/overview': typeof ApiAhrefsOverviewRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/canonry/create-project': typeof ApiCanonryCreateProjectRoute
  '/api/google/ads-customers': typeof ApiGoogleAdsCustomersRoute
  '/api/google/ads-data': typeof ApiGoogleAdsDataRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connection': typeof ApiGoogleConnectionRoute
  '/api/google/ga4-conversions': typeof ApiGoogleGa4ConversionsRoute
  '/api/google/ga4-properties': typeof ApiGoogleGa4PropertiesRoute
  '/api/google/ga4-summary': typeof ApiGoogleGa4SummaryRoute
  '/api/google/ga4-traffic': typeof ApiGoogleGa4TrafficRoute
  '/api/google/gsc-import': typeof ApiGoogleGscImportRoute
  '/api/google/gsc-sites': typeof ApiGoogleGscSitesRoute
  '/api/google/pagespeed': typeof ApiGooglePagespeedRoute
  '/api/live/status': typeof ApiLiveStatusRoute
  '/api/perplexity/search': typeof ApiPerplexitySearchRoute
  '/api/google/oauth/start': typeof ApiGoogleOauthStartRoute
  '/api/live/canonry/ai-visibility': typeof ApiLiveCanonryAiVisibilityRoute
  '/api/live/canonry/overview': typeof ApiLiveCanonryOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/content': typeof ContentRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/geo': typeof GeoRoute
  '/github-status': typeof GithubStatusRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/content/$id': typeof ContentIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/settings/api': typeof SettingsApiRoute
  '/tasks/$id': typeof TasksIdRoute
  '/api/admin/populate': typeof ApiAdminPopulateRoute
  '/api/agent/agents': typeof ApiAgentAgentsRoute
  '/api/agent/job': typeof ApiAgentJobRoute
  '/api/agent/memory': typeof ApiAgentMemoryRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/run-agent': typeof ApiAgentRunAgentRoute
  '/api/ahrefs/overview': typeof ApiAhrefsOverviewRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/canonry/create-project': typeof ApiCanonryCreateProjectRoute
  '/api/google/ads-customers': typeof ApiGoogleAdsCustomersRoute
  '/api/google/ads-data': typeof ApiGoogleAdsDataRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connection': typeof ApiGoogleConnectionRoute
  '/api/google/ga4-conversions': typeof ApiGoogleGa4ConversionsRoute
  '/api/google/ga4-properties': typeof ApiGoogleGa4PropertiesRoute
  '/api/google/ga4-summary': typeof ApiGoogleGa4SummaryRoute
  '/api/google/ga4-traffic': typeof ApiGoogleGa4TrafficRoute
  '/api/google/gsc-import': typeof ApiGoogleGscImportRoute
  '/api/google/gsc-sites': typeof ApiGoogleGscSitesRoute
  '/api/google/pagespeed': typeof ApiGooglePagespeedRoute
  '/api/live/status': typeof ApiLiveStatusRoute
  '/api/perplexity/search': typeof ApiPerplexitySearchRoute
  '/api/google/oauth/start': typeof ApiGoogleOauthStartRoute
  '/api/live/canonry/ai-visibility': typeof ApiLiveCanonryAiVisibilityRoute
  '/api/live/canonry/overview': typeof ApiLiveCanonryOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/content'
    | '/customers'
    | '/dashboard'
    | '/geo'
    | '/github-status'
    | '/health'
    | '/login'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/admin/users'
    | '/content/$id'
    | '/customers/$id'
    | '/settings/api'
    | '/tasks/$id'
    | '/api/admin/populate'
    | '/api/agent/agents'
    | '/api/agent/job'
    | '/api/agent/memory'
    | '/api/agent/run'
    | '/api/agent/run-agent'
    | '/api/ahrefs/overview'
    | '/api/ai/generate'
    | '/api/canonry/create-project'
    | '/api/google/ads-customers'
    | '/api/google/ads-data'
    | '/api/google/callback'
    | '/api/google/connection'
    | '/api/google/ga4-conversions'
    | '/api/google/ga4-properties'
    | '/api/google/ga4-summary'
    | '/api/google/ga4-traffic'
    | '/api/google/gsc-import'
    | '/api/google/gsc-sites'
    | '/api/google/pagespeed'
    | '/api/live/status'
    | '/api/perplexity/search'
    | '/api/google/oauth/start'
    | '/api/live/canonry/ai-visibility'
    | '/api/live/canonry/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/content'
    | '/customers'
    | '/dashboard'
    | '/geo'
    | '/github-status'
    | '/health'
    | '/login'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/admin/users'
    | '/content/$id'
    | '/customers/$id'
    | '/settings/api'
    | '/tasks/$id'
    | '/api/admin/populate'
    | '/api/agent/agents'
    | '/api/agent/job'
    | '/api/agent/memory'
    | '/api/agent/run'
    | '/api/agent/run-agent'
    | '/api/ahrefs/overview'
    | '/api/ai/generate'
    | '/api/canonry/create-project'
    | '/api/google/ads-customers'
    | '/api/google/ads-data'
    | '/api/google/callback'
    | '/api/google/connection'
    | '/api/google/ga4-conversions'
    | '/api/google/ga4-properties'
    | '/api/google/ga4-summary'
    | '/api/google/ga4-traffic'
    | '/api/google/gsc-import'
    | '/api/google/gsc-sites'
    | '/api/google/pagespeed'
    | '/api/live/status'
    | '/api/perplexity/search'
    | '/api/google/oauth/start'
    | '/api/live/canonry/ai-visibility'
    | '/api/live/canonry/overview'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/content'
    | '/customers'
    | '/dashboard'
    | '/geo'
    | '/github-status'
    | '/health'
    | '/login'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/admin/users'
    | '/content/$id'
    | '/customers/$id'
    | '/settings/api'
    | '/tasks/$id'
    | '/api/admin/populate'
    | '/api/agent/agents'
    | '/api/agent/job'
    | '/api/agent/memory'
    | '/api/agent/run'
    | '/api/agent/run-agent'
    | '/api/ahrefs/overview'
    | '/api/ai/generate'
    | '/api/canonry/create-project'
    | '/api/google/ads-customers'
    | '/api/google/ads-data'
    | '/api/google/callback'
    | '/api/google/connection'
    | '/api/google/ga4-conversions'
    | '/api/google/ga4-properties'
    | '/api/google/ga4-summary'
    | '/api/google/ga4-traffic'
    | '/api/google/gsc-import'
    | '/api/google/gsc-sites'
    | '/api/google/pagespeed'
    | '/api/live/status'
    | '/api/perplexity/search'
    | '/api/google/oauth/start'
    | '/api/live/canonry/ai-visibility'
    | '/api/live/canonry/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ContentRoute: typeof ContentRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  GeoRoute: typeof GeoRoute
  GithubStatusRoute: typeof GithubStatusRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  ApiAdminPopulateRoute: typeof ApiAdminPopulateRoute
  ApiAgentAgentsRoute: typeof ApiAgentAgentsRoute
  ApiAgentJobRoute: typeof ApiAgentJobRoute
  ApiAgentMemoryRoute: typeof ApiAgentMemoryRoute
  ApiAgentRunRoute: typeof ApiAgentRunRoute
  ApiAgentRunAgentRoute: typeof ApiAgentRunAgentRoute
  ApiAhrefsOverviewRoute: typeof ApiAhrefsOverviewRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiCanonryCreateProjectRoute: typeof ApiCanonryCreateProjectRoute
  ApiGoogleAdsCustomersRoute: typeof ApiGoogleAdsCustomersRoute
  ApiGoogleAdsDataRoute: typeof ApiGoogleAdsDataRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleConnectionRoute: typeof ApiGoogleConnectionRoute
  ApiGoogleGa4ConversionsRoute: typeof ApiGoogleGa4ConversionsRoute
  ApiGoogleGa4PropertiesRoute: typeof ApiGoogleGa4PropertiesRoute
  ApiGoogleGa4SummaryRoute: typeof ApiGoogleGa4SummaryRoute
  ApiGoogleGa4TrafficRoute: typeof ApiGoogleGa4TrafficRoute
  ApiGoogleGscImportRoute: typeof ApiGoogleGscImportRoute
  ApiGoogleGscSitesRoute: typeof ApiGoogleGscSitesRoute
  ApiGooglePagespeedRoute: typeof ApiGooglePagespeedRoute
  ApiLiveStatusRoute: typeof ApiLiveStatusRoute
  ApiPerplexitySearchRoute: typeof ApiPerplexitySearchRoute
  ApiGoogleOauthStartRoute: typeof ApiGoogleOauthStartRoute
  ApiLiveCanonryAiVisibilityRoute: typeof ApiLiveCanonryAiVisibilityRoute
  ApiLiveCanonryOverviewRoute: typeof ApiLiveCanonryOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-status': {
      id: '/github-status'
      path: '/github-status'
      fullPath: '/github-status'
      preLoaderRoute: typeof GithubStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/settings/api': {
      id: '/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof SettingsApiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof ContentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/perplexity/search': {
      id: '/api/perplexity/search'
      path: '/api/perplexity/search'
      fullPath: '/api/perplexity/search'
      preLoaderRoute: typeof ApiPerplexitySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/status': {
      id: '/api/live/status'
      path: '/api/live/status'
      fullPath: '/api/live/status'
      preLoaderRoute: typeof ApiLiveStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/pagespeed': {
      id: '/api/google/pagespeed'
      path: '/api/google/pagespeed'
      fullPath: '/api/google/pagespeed'
      preLoaderRoute: typeof ApiGooglePagespeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/gsc-sites': {
      id: '/api/google/gsc-sites'
      path: '/api/google/gsc-sites'
      fullPath: '/api/google/gsc-sites'
      preLoaderRoute: typeof ApiGoogleGscSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/gsc-import': {
      id: '/api/google/gsc-import'
      path: '/api/google/gsc-import'
      fullPath: '/api/google/gsc-import'
      preLoaderRoute: typeof ApiGoogleGscImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/ga4-traffic': {
      id: '/api/google/ga4-traffic'
      path: '/api/google/ga4-traffic'
      fullPath: '/api/google/ga4-traffic'
      preLoaderRoute: typeof ApiGoogleGa4TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/ga4-summary': {
      id: '/api/google/ga4-summary'
      path: '/api/google/ga4-summary'
      fullPath: '/api/google/ga4-summary'
      preLoaderRoute: typeof ApiGoogleGa4SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/ga4-properties': {
      id: '/api/google/ga4-properties'
      path: '/api/google/ga4-properties'
      fullPath: '/api/google/ga4-properties'
      preLoaderRoute: typeof ApiGoogleGa4PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/ga4-conversions': {
      id: '/api/google/ga4-conversions'
      path: '/api/google/ga4-conversions'
      fullPath: '/api/google/ga4-conversions'
      preLoaderRoute: typeof ApiGoogleGa4ConversionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/connection': {
      id: '/api/google/connection'
      path: '/api/google/connection'
      fullPath: '/api/google/connection'
      preLoaderRoute: typeof ApiGoogleConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/ads-data': {
      id: '/api/google/ads-data'
      path: '/api/google/ads-data'
      fullPath: '/api/google/ads-data'
      preLoaderRoute: typeof ApiGoogleAdsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/ads-customers': {
      id: '/api/google/ads-customers'
      path: '/api/google/ads-customers'
      fullPath: '/api/google/ads-customers'
      preLoaderRoute: typeof ApiGoogleAdsCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canonry/create-project': {
      id: '/api/canonry/create-project'
      path: '/api/canonry/create-project'
      fullPath: '/api/canonry/create-project'
      preLoaderRoute: typeof ApiCanonryCreateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ahrefs/overview': {
      id: '/api/ahrefs/overview'
      path: '/api/ahrefs/overview'
      fullPath: '/api/ahrefs/overview'
      preLoaderRoute: typeof ApiAhrefsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/run-agent': {
      id: '/api/agent/run-agent'
      path: '/api/agent/run-agent'
      fullPath: '/api/agent/run-agent'
      preLoaderRoute: typeof ApiAgentRunAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/run': {
      id: '/api/agent/run'
      path: '/api/agent/run'
      fullPath: '/api/agent/run'
      preLoaderRoute: typeof ApiAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/memory': {
      id: '/api/agent/memory'
      path: '/api/agent/memory'
      fullPath: '/api/agent/memory'
      preLoaderRoute: typeof ApiAgentMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/job': {
      id: '/api/agent/job'
      path: '/api/agent/job'
      fullPath: '/api/agent/job'
      preLoaderRoute: typeof ApiAgentJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/agents': {
      id: '/api/agent/agents'
      path: '/api/agent/agents'
      fullPath: '/api/agent/agents'
      preLoaderRoute: typeof ApiAgentAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/populate': {
      id: '/api/admin/populate'
      path: '/api/admin/populate'
      fullPath: '/api/admin/populate'
      preLoaderRoute: typeof ApiAdminPopulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/canonry/overview': {
      id: '/api/live/canonry/overview'
      path: '/api/live/canonry/overview'
      fullPath: '/api/live/canonry/overview'
      preLoaderRoute: typeof ApiLiveCanonryOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/canonry/ai-visibility': {
      id: '/api/live/canonry/ai-visibility'
      path: '/api/live/canonry/ai-visibility'
      fullPath: '/api/live/canonry/ai-visibility'
      preLoaderRoute: typeof ApiLiveCanonryAiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth/start': {
      id: '/api/google/oauth/start'
      path: '/api/google/oauth/start'
      fullPath: '/api/google/oauth/start'
      preLoaderRoute: typeof ApiGoogleOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContentRouteChildren {
  ContentIdRoute: typeof ContentIdRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentIdRoute: ContentIdRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApiRoute: typeof SettingsApiRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiRoute: SettingsApiRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ContentRoute: ContentRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  GeoRoute: GeoRoute,
  GithubStatusRoute: GithubStatusRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  ApiAdminPopulateRoute: ApiAdminPopulateRoute,
  ApiAgentAgentsRoute: ApiAgentAgentsRoute,
  ApiAgentJobRoute: ApiAgentJobRoute,
  ApiAgentMemoryRoute: ApiAgentMemoryRoute,
  ApiAgentRunRoute: ApiAgentRunRoute,
  ApiAgentRunAgentRoute: ApiAgentRunAgentRoute,
  ApiAhrefsOverviewRoute: ApiAhrefsOverviewRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiCanonryCreateProjectRoute: ApiCanonryCreateProjectRoute,
  ApiGoogleAdsCustomersRoute: ApiGoogleAdsCustomersRoute,
  ApiGoogleAdsDataRoute: ApiGoogleAdsDataRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleConnectionRoute: ApiGoogleConnectionRoute,
  ApiGoogleGa4ConversionsRoute: ApiGoogleGa4ConversionsRoute,
  ApiGoogleGa4PropertiesRoute: ApiGoogleGa4PropertiesRoute,
  ApiGoogleGa4SummaryRoute: ApiGoogleGa4SummaryRoute,
  ApiGoogleGa4TrafficRoute: ApiGoogleGa4TrafficRoute,
  ApiGoogleGscImportRoute: ApiGoogleGscImportRoute,
  ApiGoogleGscSitesRoute: ApiGoogleGscSitesRoute,
  ApiGooglePagespeedRoute: ApiGooglePagespeedRoute,
  ApiLiveStatusRoute: ApiLiveStatusRoute,
  ApiPerplexitySearchRoute: ApiPerplexitySearchRoute,
  ApiGoogleOauthStartRoute: ApiGoogleOauthStartRoute,
  ApiLiveCanonryAiVisibilityRoute: ApiLiveCanonryAiVisibilityRoute,
  ApiLiveCanonryOverviewRoute: ApiLiveCanonryOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
