// Typ-Oberflaeche des extrahierten Moduls (21.08.2026) — bewusst lose:
// die Implementierung ist .jsx; TS-Importeure bekommen ComponentType/any.
import type * as React from "react";

export const CTooltip: React.ComponentType<any>;
export const CalendarMonth: React.ComponentType<any>;
export const ChartCard: React.ComponentType<any>;
export const CompareBanner: React.ComponentType<any>;
export const ComparePicker: React.ComponentType<any>;
export const DTable: React.ComponentType<any>;
export const DateRangePicker: React.ComponentType<any>;
export const Inp: React.ComponentType<any>;
export const KpiCard: React.ComponentType<any>;
export const LiveEmptyState: React.ComponentType<any>;
export const Modal: React.ComponentType<any>;
export const PBadge: React.ComponentType<any>;
export const SectionErrorBoundary: React.ComponentType<any>;
export const SectionPlaceholder: React.ComponentType<any>;
export const SeoPager: React.ComponentType<any>;
export const Skeleton: React.ComponentType<any>;
export const TabBar: React.ComponentType<any>;
export const AI_COLORS: any;
export const API_BASE_URL: any;
export const CANONRY_PROVIDER_LABELS: any;
export const CANONRY_SERVICE: any;
export const CLIENT_STORAGE_KEY: any;
export const COMPARE_OPTIONS: any;
export const DEFAULTS_STORAGE_KEY: any;
export const DEFAULT_CUSTOMER_DEFAULTS: any;
export const DEFAULT_PROFILE: any;
export const DRP: any;
export const MONTHS: any;
export const PROFILE_STORAGE_KEY: any;
export const WEEKDAYS: any;
export const liveDaysFor: any;
export function apiUrl(...args: any[]): any;
export function buildCanonryEvidenceRows(...args: any[]): any;
export function buildCanonryHealthDistribution(...args: any[]): any;
export function buildCanonryLiveModel(...args: any[]): any;
export function buildCanonryProviderBreakdown(...args: any[]): any;
export function buildCanonryProviderSeries(...args: any[]): any;
export function canonryProviderLabel(...args: any[]): any;
export function clientFormFromClient(...args: any[]): any;
export function compareName(...args: any[]): any;
export function computeCompareRange(...args: any[]): any;
export function defaultsFromStored(...args: any[]): any;
export function downloadFile(...args: any[]): any;
export function formatCanonryDay(...args: any[]): any;
export function formatCanonryDuration(...args: any[]): any;
export function formatCanonryStamp(...args: any[]): any;
export function ga4PropertyText(...args: any[]): any;
export function initialsFromName(...args: any[]): any;
export function normalizeClientShape(...args: any[]): any;
export function parseCanonryErrorMap(...args: any[]): any;
export function parseSeriesDate(...args: any[]): any;
export function pctDelta(...args: any[]): any;
export function persistJson(...args: any[]): any;
export function profileFromStored(...args: any[]): any;
export function readStoredJson(...args: any[]): any;
export function seoPageNums(...args: any[]): any;
export function seriesDelta(...args: any[]): any;
export function slugifyProjectName(...args: any[]): any;
export function splitCsv(...args: any[]): any;
export function sumSeriesInRange(...args: any[]): any;
export function useCanonryOverview(...args: any[]): any;
export function useGa4Compare(...args: any[]): any;
export function useLiveGa4(...args: any[]): any;
export function useLiveIntegrations(...args: any[]): any;
export function useMediaQuery(...args: any[]): any;
